
types:
  - cleanup
  - build
  - test
  - deploy

job_build:
  type: build
  script:
  - pwd
  - curl https://install.meteor.com/ | sh
  - meteor npm install
  - sudo npm install --global mup
  only:
  - master
  tags:
  - master

job_test:
  type: test
  script:
  - echo "testing ----"
  - npm run test
  only:
  - master
  tags:
  - master

job_deploy:
  type: deploy
  script:
  - echo "deploying ----"
  # - cd /home/gitlab-runner/erecaho-build/server-alpha-running/bundle/programs/server/ && /home/gitlab-runner/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/dev_bundle/bin/npm install
  - cd /.deploy
  - sudo mup setup
  - sudo mup deploy
  only:
  - master
  tags:
  - master