image: node:4.2.2
image: christiankiely/meteord:test

before_script:
  # - apt-get update -y
  # - apt-get install locales -y
  # - locale-gen en_US.UTF-8
  # - localedef -i en_GB -f UTF-8 en_US.UTF-8
  # - dpkg-reconfigure locales
  # - echo export LC_ALL=C >> ~/.bashrc
  # - source ~/.bashrc
  - meteor npm install
  - npm install --global mup

types:
  - cleanup
  - build
  - test
  - deploy

job_build:
  type: build
  script:
  - pwd
  only:
  - master
  tags:
  - master

job_test:
  type: test
  script:
  - echo "testing ----"
  - npm run test
  only:
  - master
  tags:
  - master

job_deploy:
  type: deploy
  script:
  - echo "deploying ----"
  # - cd /home/gitlab-runner/erecaho-build/server-alpha-running/bundle/programs/server/ && /home/gitlab-runner/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/dev_bundle/bin/npm install
  - cd /.deploy
  - mup setup
  - mup deploy
  only:
  - master
  tags:
  - master