version: 2.1
jobs: 
  build:
    working_directory: ~/simple-todos
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: "install Meteor"
          command: |  
            curl https://install.meteor.com | sh
      - run:
          name: "install npm package"
          command: |
            npm install
      - run:
          name: "listing"
          command: |
            ls -a
      - save_cache:
          key: npm-packages-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ./node_modules/
